<?php declare(strict_types=1);

namespace Collectiq\SolanaPhpSdk\Tests\Unit\Programs\SNS;

use Collectiq\SolanaPhpSdk\Connection;
use Collectiq\SolanaPhpSdk\Enum\Network;
use Collectiq\SolanaPhpSdk\Programs\SNS\State\NameRegistryStateAccount;
use Collectiq\SolanaPhpSdk\Tests\TestCase;
use Collectiq\SolanaPhpSdk\Util\Buffer;
use PHPUnit\Framework\Attributes\Test;

final class NameRegistryStateTest extends TestCase
{
    #[Test]
    public function deserialize(): void
    {
        $accountData = 'PVPCSzg2DtOBOiPfst/YIKtYIct5KaONLqqyUug4JZXybLcicCAgnC2mdJSPjzwzDuT5o4Yla9FPN6bgxWdUKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY2x1ZTIuc29sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==';

        $nameRegistryState = NameRegistryStateAccount::deserialize(
            Buffer::fromString(base64_decode($accountData))->toArray()
        );

        $this->assertEquals('58PwtjSDuFHuUkYjH9BYnnQKHfwo9reZhC2zMJv9JPkx', $nameRegistryState->parentName->toBase58());
        $this->assertEquals('HKKp49qGWXd639QsuH7JiLijfVW5UtCVY4s1n2HANwEA', $nameRegistryState->owner->toBase58());
        $this->assertEquals('11111111111111111111111111111111', $nameRegistryState->class->toBase58());
    }

    #[Test]
    public function retrieve(): void
    {
        config(['solana-php-sdk.network' => Network::MAINNET]);

        $connection = $this->container->get(Connection::class);

        $nameRegistryState = NameRegistryStateAccount::retrieve($connection, 'Crf8hzfthWGbGbLTVCiqRqV5MVnbpHB1L9KQMd6gsinb');

        $this->assertEquals('HKKp49qGWXd639QsuH7JiLijfVW5UtCVY4s1n2HANwEA', $nameRegistryState['registry']->owner->toBase58());
        $this->assertEquals('58PwtjSDuFHuUkYjH9BYnnQKHfwo9reZhC2zMJv9JPkx', $nameRegistryState['registry']->parentName->toBase58());
        $this->assertEquals('11111111111111111111111111111111', $nameRegistryState['registry']->class->toBase58());
    }
}
